name: Record Website
on:
  push:
    branches:
      - main

jobs:
  record-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install selenium chromedriver
      - name: Record website
        run: python record_website.py
      - name: Move recording file to root
        run: mv recording.mp4 .
